### ISSUE TITLE
Negative gauges probably broken

### ISSUE THREAD

**Issue by timmc** [pyr/clj-statsd#11]
Through no fault of your own, the gauge protocol is broken for negative values. You may wish to take defensive action.

If statsd receives a gauge value of `-5`, it _subtracts_ 5 from the current value. (Likewise, `+5` adds to the current value.) I would recommend either:
- documenting that negative values are unsupported, or
- sending a value of `0` followed by the negative value (although since UDP does not have delivery order guarantees, this is suspect as well)

**Comment by jlopp** [comment]
:+1: I just ran into this and consider it to be unexpected behavior

**Comment by pyr** [comment]
fixed in 0d9e13d

**Comment by pyr** [comment]
fixed in 0d9e13d
