### ISSUE TITLE
[doc] Request for a CHANGELOG

### ISSUE THREAD

**Issue by vedang** [pyr/clj-statsd#19]
Hi All,

I'm upgrading the clj-statsd library in a production codebase from `0.3.10` to `0.4.0`. I could not find a changelog file or the tag `0.3.10` in the git history of this project. Could you please tell me if this is a breaking upgrade or not?

Thanks!

**Comment by pyr** [comment]
hi @vedang,

No breaking change in this release, I'll work on maintaining a better release changelog, thanks for the prompt!

**Comment by vedang** [comment]
Hi @pyr,

Actually, the `send-stat` function has changed from accepting a single argument `content` to 3 arguments : `prefix`, `content`, `tags`.

This change broke a number of tests in the codebase where the `send-stat` function was mocked out with a `redef`!  No other breakage though, thanks for creating and maintaining such a nice library :)
